version: '3.8'

services:
  producer:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    command: npm run dev:producer
    volumes:
      - .:/app
      - /app/node_modules
  worker:
    build: .
    environment:
      NODE_ENV: development
    command: npm run dev:worker
    volumes:
      - .:/app
      - /app/node_modules
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ default port for messaging
      - '15672:15672' # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
